# Generated by Django 3.0 on 2019-12-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
                ('author', models.CharField(max_length=250, null=True)),
                ('content', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('published', models.BooleanField(default=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
