# Generated by Django 3.0 on 2019-12-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saying',
            name='video',
            field=models.TextField(null=True),
        ),
    ]
