# Generated by Django 3.0 on 2019-12-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_saying_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='saying',
            name='fullname',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
