# Generated by Django 3.0 on 2019-12-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=250, null=True)),
                ('lname', models.CharField(max_length=250, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('gender', models.CharField(max_length=8, null=True)),
                ('position', models.CharField(max_length=250, null=True)),
                ('age', models.CharField(max_length=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
