# Generated by Django 3.0 on 2019-12-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='experience',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
