# Generated by Django 3.0 on 2019-12-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=250, null=True)),
                ('lname', models.CharField(max_length=250, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('address', models.TextField(null=True)),
                ('datetime', models.CharField(max_length=250, null=True)),
                ('service', models.CharField(max_length=250, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
